# Generated by Django 3.2.5 on 2021-07-09 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=3)),
                ('wiki_link', models.CharField(max_length=150, null=True)),
                ('anthem', models.CharField(max_length=150, null=True)),
                ('globe_map', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=150)),
                ('photo_url', models.CharField(max_length=150)),
                ('about_me', models.TextField(max_length=350, null=True)),
                ('country_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='world_spectacular_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='User_Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited', models.BooleanField(default=False)),
                ('dream_visit', models.BooleanField(default=False)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_country_visit', to='world_spectacular_app.country')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_visit', to='world_spectacular_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Country_Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_url', models.CharField(max_length=150)),
                ('picture_location', models.CharField(max_length=150)),
                ('picture_photographer', models.CharField(max_length=150, null=True)),
                ('picture_photographer_link', models.CharField(max_length=150, null=True)),
                ('picture_source', models.CharField(max_length=150, null=True)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='world_spectacular_app.country')),
            ],
        ),
    ]
