# Generated by Django 3.2.5 on 2021-07-09 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world_spectacular_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country_picture',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='user_visit',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='user_visit',
            old_name='user_id',
            new_name='user',
        ),
    ]
