# Generated by Django 3.2.5 on 2021-07-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_spectacular_app', '0002_auto_20210709_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='anthem',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='globe_map',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='wiki_link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='country_picture',
            name='picture_photographer_link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='country_picture',
            name='picture_source',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='country_picture',
            name='picture_url',
            field=models.CharField(max_length=500),
        ),
    ]
