# Generated by Django 3.2.5 on 2021-07-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_spectacular_app', '0003_auto_20210711_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='anthem',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='globe_map',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='country',
            name='wiki_link',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='country_picture',
            name='picture_location',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='country_picture',
            name='picture_photographer',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='country_picture',
            name='picture_photographer_link',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='country_picture',
            name='picture_source',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
