# Generated by Django 3.2.5 on 2021-07-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_spectacular_app', '0004_auto_20210712_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_picture',
            name='picture_photographer_link',
            field=models.CharField(default=None, max_length=1500),
        ),
        migrations.AlterField(
            model_name='country_picture',
            name='picture_source',
            field=models.CharField(default=None, max_length=1500),
        ),
        migrations.AlterField(
            model_name='country_picture',
            name='picture_url',
            field=models.CharField(max_length=1500),
        ),
    ]
