# Generated by Django 3.2.5 on 2021-07-14 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world_spectacular_app', '0005_auto_20210712_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AlterField(
            model_name='user',
            name='about_me',
            field=models.TextField(default=None, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='world_spectacular_app.country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_url',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
